// Voltti mock product catalog — Nordic electronics store, EUR pricing.
import type { Category, Product } from "./types";

export const products: Product[] = [
  // ---------------------------------------------------------------- phones
  {
    id: "iphone-16-pro",
    name: "Apple iPhone 16 Pro 256GB",
    brand: "Apple",
    category: "phones",
    subcategory: "flagship-phone",
    price: 1199,
    originalPrice: 1329,
    stock: 24,
    rating: 4.8,
    reviewCount: 2417,
    tags: ["apple", "iphone", "ios", "5g", "camera", "titanium"],
    blurb: "Apple's titanium flagship with the A18 Pro chip and a pro-grade camera system.",
    description:
      "The iPhone 16 Pro pairs a 6.3-inch Super Retina XDR display with the blisteringly fast A18 Pro chip. A new 48MP Fusion camera, Camera Control button, and Apple Intelligence features make it the most capable iPhone yet.",
    highlights: [
      "A18 Pro chip with Apple Intelligence",
      "48MP Fusion camera with 5x telephoto",
      "Grade 5 titanium design",
      "Camera Control button for instant capture",
    ],
    specs: {
      Display: "6.3\" Super Retina XDR OLED, 120 Hz ProMotion",
      Chip: "Apple A18 Pro",
      Storage: "256 GB",
      Camera: "48MP main + 48MP ultra-wide + 12MP 5x telephoto",
      Battery: "Up to 27 h video playback",
      Connectivity: "5G, Wi-Fi 7, USB-C 3",
      Weight: "199 g",
    },
    visual: "phone",
    accent: "#8a8d92",
  },
  {
    id: "iphone-16",
    name: "Apple iPhone 16 128GB",
    brand: "Apple",
    category: "phones",
    subcategory: "flagship-phone",
    price: 949,
    stock: 31,
    rating: 4.7,
    reviewCount: 1854,
    tags: ["apple", "iphone", "ios", "5g", "camera"],
    blurb: "The everyday iPhone with the A18 chip, Camera Control, and bold new colours.",
    description:
      "The iPhone 16 brings the A18 chip, a 48MP Fusion camera, and the new Camera Control button to the mainstream lineup. Apple Intelligence and all-day battery life round out a phone that does almost everything the Pro does.",
    highlights: [
      "A18 chip with Apple Intelligence",
      "48MP Fusion camera with 2x optical-quality zoom",
      "Action button and Camera Control",
      "All-day battery life",
    ],
    specs: {
      Display: "6.1\" Super Retina XDR OLED, 60 Hz",
      Chip: "Apple A18",
      Storage: "128 GB",
      Camera: "48MP main + 12MP ultra-wide",
      Battery: "Up to 22 h video playback",
      Connectivity: "5G, Wi-Fi 7, USB-C",
      Weight: "170 g",
    },
    visual: "phone",
    accent: "#5fa8e8",
  },
  {
    id: "galaxy-s25-ultra",
    name: "Samsung Galaxy S25 Ultra 256GB",
    brand: "Samsung",
    category: "phones",
    subcategory: "flagship-phone",
    price: 1349,
    stock: 0,
    rating: 4.8,
    reviewCount: 1962,
    tags: ["samsung", "android", "5g", "camera", "s-pen", "titanium"],
    blurb: "Samsung's ultimate flagship with a 200MP camera, S Pen, and Galaxy AI.",
    description:
      "The Galaxy S25 Ultra combines a Snapdragon 8 Elite chip with a 200MP main camera and a gorgeous 6.9-inch QHD+ display. The built-in S Pen and Galaxy AI features make it the productivity king of Android phones.",
    highlights: [
      "200MP main camera with 100x Space Zoom",
      "Snapdragon 8 Elite for Galaxy",
      "Built-in S Pen",
      "Titanium frame with Gorilla Armor 2",
    ],
    specs: {
      Display: "6.9\" Dynamic AMOLED 2X, QHD+, 120 Hz",
      Chip: "Snapdragon 8 Elite for Galaxy",
      RAM: "12 GB",
      Storage: "256 GB",
      Camera: "200MP main + 50MP ultra-wide + 50MP 5x + 10MP 3x",
      Battery: "5000 mAh, 45 W fast charging",
      Weight: "218 g",
    },
    visual: "phone",
    accent: "#3b4a6b",
  },
  {
    id: "galaxy-s25",
    name: "Samsung Galaxy S25 128GB",
    brand: "Samsung",
    category: "phones",
    subcategory: "flagship-phone",
    price: 899,
    stock: 27,
    rating: 4.6,
    reviewCount: 1108,
    tags: ["samsung", "android", "5g", "camera", "compact"],
    blurb: "A compact Android flagship with Snapdragon 8 Elite power and seven years of updates.",
    description:
      "The Galaxy S25 packs flagship performance into a light 162-gram body. With the Snapdragon 8 Elite, a versatile triple camera, and seven years of OS updates, it is one of the easiest Android phones to recommend.",
    highlights: [
      "Snapdragon 8 Elite for Galaxy",
      "Compact 6.2\" 120 Hz AMOLED display",
      "50MP triple camera with Galaxy AI editing",
      "7 years of OS and security updates",
    ],
    specs: {
      Display: "6.2\" Dynamic AMOLED 2X, 120 Hz",
      Chip: "Snapdragon 8 Elite for Galaxy",
      RAM: "12 GB",
      Storage: "128 GB",
      Camera: "50MP main + 12MP ultra-wide + 10MP 3x telephoto",
      Battery: "4000 mAh, 25 W charging",
      Weight: "162 g",
    },
    visual: "phone",
    accent: "#7fb2e5",
  },
  {
    id: "pixel-9-pro",
    name: "Google Pixel 9 Pro 256GB",
    brand: "Google",
    category: "phones",
    subcategory: "flagship-phone",
    price: 1099,
    stock: 18,
    rating: 4.7,
    reviewCount: 1336,
    tags: ["google", "pixel", "android", "5g", "camera", "ai"],
    blurb: "Google's AI-first flagship with the best computational photography in the business.",
    description:
      "The Pixel 9 Pro brings Gemini AI deep into the phone experience, backed by the Tensor G4 chip and a stunning 6.3-inch Super Actua display. Its 50MP triple camera with Magic Editor remains the benchmark for point-and-shoot photography.",
    highlights: [
      "Tensor G4 with on-device Gemini Nano",
      "50MP triple camera with 5x telephoto",
      "Super Actua display up to 3000 nits",
      "7 years of OS updates",
    ],
    specs: {
      Display: "6.3\" LTPO OLED, 1-120 Hz, 3000 nits peak",
      Chip: "Google Tensor G4",
      RAM: "16 GB",
      Storage: "256 GB",
      Camera: "50MP main + 48MP ultra-wide + 48MP 5x telephoto",
      Battery: "4700 mAh, 27 W charging",
      Weight: "199 g",
    },
    visual: "phone",
    accent: "#c7b9a8",
  },
  {
    id: "pixel-9a",
    name: "Google Pixel 9a 128GB",
    brand: "Google",
    category: "phones",
    subcategory: "budget-phone",
    price: 449,
    originalPrice: 549,
    stock: 42,
    rating: 4.6,
    reviewCount: 887,
    tags: ["google", "pixel", "android", "5g", "budget", "camera"],
    blurb: "Flagship-grade camera and Tensor G4 smarts at a mid-range price.",
    description:
      "The Pixel 9a delivers the same Tensor G4 chip as the flagship Pixels at a fraction of the price. With a bright 120 Hz display, a great 48MP camera, and seven years of updates, it is the value king of Android.",
    highlights: [
      "Tensor G4 chip with Gemini AI features",
      "48MP camera with Magic Eraser",
      "6.3\" 120 Hz Actua display",
      "7 years of OS and security updates",
    ],
    specs: {
      Display: "6.3\" OLED, 120 Hz, 2700 nits peak",
      Chip: "Google Tensor G4",
      RAM: "8 GB",
      Storage: "128 GB",
      Camera: "48MP main + 13MP ultra-wide",
      Battery: "5100 mAh, 23 W charging",
      Weight: "186 g",
    },
    visual: "phone",
    accent: "#7aa874",
  },
  {
    id: "oneplus-13",
    name: "OnePlus 13 256GB",
    brand: "OnePlus",
    category: "phones",
    subcategory: "flagship-phone",
    price: 999,
    stock: 14,
    rating: 4.6,
    reviewCount: 612,
    tags: ["oneplus", "android", "5g", "fast-charging", "hasselblad"],
    blurb: "Snapdragon 8 Elite speed, a Hasselblad camera, and 100 W charging that fills up in minutes.",
    description:
      "The OnePlus 13 is a performance monster with the Snapdragon 8 Elite and a huge 6000 mAh silicon-carbon battery. Hasselblad-tuned cameras and 100 W SUPERVOOC charging make it a flagship that never slows you down.",
    highlights: [
      "Snapdragon 8 Elite performance",
      "6000 mAh battery with 100 W charging",
      "Hasselblad-tuned 50MP triple camera",
      "IP69 dust and water resistance",
    ],
    specs: {
      Display: "6.82\" LTPO AMOLED, QHD+, 120 Hz",
      Chip: "Snapdragon 8 Elite",
      RAM: "12 GB",
      Storage: "256 GB",
      Camera: "50MP main + 50MP ultra-wide + 50MP 3x periscope",
      Battery: "6000 mAh, 100 W SUPERVOOC",
      Weight: "213 g",
    },
    visual: "phone",
    accent: "#d64545",
  },
  {
    id: "nothing-phone-3a",
    name: "Nothing Phone (3a) 128GB",
    brand: "Nothing",
    category: "phones",
    subcategory: "budget-phone",
    price: 329,
    originalPrice: 379,
    stock: 38,
    rating: 4.4,
    reviewCount: 421,
    tags: ["nothing", "android", "5g", "budget", "glyph", "design"],
    blurb: "The transparent-design mid-ranger with Glyph lights and a clean Nothing OS experience.",
    description:
      "The Nothing Phone (3a) stands out with its transparent back and signature Glyph interface lights. Under the hood, a Snapdragon 7s Gen 3 and a 50MP triple camera deliver way more than you would expect at this price.",
    highlights: [
      "Iconic transparent design with Glyph lights",
      "Bright 6.77\" 120 Hz AMOLED display",
      "50MP triple camera with 2x telephoto",
      "Clean, fast Nothing OS 3.1",
    ],
    specs: {
      Display: "6.77\" AMOLED, 120 Hz, 3000 nits peak",
      Chip: "Snapdragon 7s Gen 3",
      RAM: "8 GB",
      Storage: "128 GB",
      Camera: "50MP main + 50MP 2x telephoto + 8MP ultra-wide",
      Battery: "5000 mAh, 50 W charging",
      Weight: "201 g",
    },
    visual: "phone",
    accent: "#1c1c1e",
  },

  // --------------------------------------------------------------- laptops
  {
    id: "legion-pro-5-16",
    name: "Lenovo Legion Pro 5 16 (RTX 4070)",
    brand: "Lenovo",
    category: "laptops",
    subcategory: "gaming-laptop",
    price: 1599,
    originalPrice: 1899,
    stock: 12,
    rating: 4.7,
    reviewCount: 743,
    tags: ["gaming", "lenovo", "legion", "rtx-4070", "240hz", "rgb"],
    blurb: "A 16-inch gaming powerhouse pairing the RTX 4070 with a 240 Hz QHD+ display.",
    description:
      "The Legion Pro 5 16 is the sweet spot of gaming laptops: a Ryzen 7 7745HX and a 140 W RTX 4070 drive its 240 Hz QHD+ panel with ease. Legion ColdFront cooling keeps it quiet under sustained load.",
    highlights: [
      "GeForce RTX 4070 at full 140 W TGP",
      "16\" QHD+ 240 Hz display, 100% sRGB",
      "Legion ColdFront 5.0 cooling",
      "Per-key RGB keyboard",
    ],
    specs: {
      Display: "16\" QHD+ (2560x1600) IPS, 240 Hz",
      CPU: "AMD Ryzen 7 7745HX",
      GPU: "NVIDIA GeForce RTX 4070 Laptop, 140 W",
      RAM: "16 GB DDR5-5600",
      Storage: "1 TB NVMe SSD",
      Battery: "80 Wh",
      Weight: "2.5 kg",
    },
    visual: "laptop",
    accent: "#3b6fd4",
  },
  {
    id: "rog-strix-g16",
    name: "ASUS ROG Strix G16 (RTX 4060)",
    brand: "ASUS",
    category: "laptops",
    subcategory: "gaming-laptop",
    price: 1399,
    stock: 16,
    rating: 4.5,
    reviewCount: 528,
    tags: ["gaming", "asus", "rog", "rtx-4060", "165hz", "rgb"],
    blurb: "ROG styling and an RTX 4060 make this 16-incher a reliable 1080p/1440p gamer.",
    description:
      "The ROG Strix G16 combines an Intel Core i7-13650HX with a GeForce RTX 4060 and a fast 165 Hz display. Tri-fan cooling and ROG's Armoury Crate tuning give you headroom for long gaming sessions.",
    highlights: [
      "GeForce RTX 4060 with MUX switch",
      "16\" FHD+ 165 Hz display",
      "Intel Core i7-13650HX",
      "Aura Sync RGB light bar",
    ],
    specs: {
      Display: "16\" FHD+ (1920x1200) IPS, 165 Hz",
      CPU: "Intel Core i7-13650HX",
      GPU: "NVIDIA GeForce RTX 4060 Laptop, 140 W",
      RAM: "16 GB DDR5-4800",
      Storage: "512 GB NVMe SSD",
      Battery: "90 Wh",
      Weight: "2.5 kg",
    },
    visual: "laptop",
    accent: "#e23a4e",
  },
  {
    id: "acer-nitro-v-15",
    name: "Acer Nitro V 15 (RTX 4050)",
    brand: "Acer",
    category: "laptops",
    subcategory: "gaming-laptop",
    price: 899,
    stock: 22,
    rating: 4.3,
    reviewCount: 391,
    tags: ["gaming", "acer", "nitro", "rtx-4050", "budget", "144hz"],
    blurb: "Entry-level gaming done right: RTX 4050 graphics and a 144 Hz display under €900.",
    description:
      "The Nitro V 15 is the budget gaming pick that does not feel budget. An RTX 4050 with DLSS 3 handles modern titles at 1080p, while the 144 Hz IPS panel keeps the action smooth.",
    highlights: [
      "GeForce RTX 4050 with DLSS 3",
      "15.6\" FHD 144 Hz display",
      "Intel Core i5-13420H",
      "Easy RAM and SSD upgrades",
    ],
    specs: {
      Display: "15.6\" FHD (1920x1080) IPS, 144 Hz",
      CPU: "Intel Core i5-13420H",
      GPU: "NVIDIA GeForce RTX 4050 Laptop, 75 W",
      RAM: "16 GB DDR5-5200",
      Storage: "512 GB NVMe SSD",
      Battery: "57 Wh",
      Weight: "2.1 kg",
    },
    visual: "laptop",
    accent: "#d8262f",
  },
  {
    id: "macbook-air-13-m4",
    name: "Apple MacBook Air 13 M4",
    brand: "Apple",
    category: "laptops",
    subcategory: "ultrabook",
    price: 1199,
    stock: 28,
    rating: 4.9,
    reviewCount: 1576,
    tags: ["apple", "macbook", "m4", "ultrabook", "fanless", "macos"],
    blurb: "The fanless M4 MacBook Air: silent, all-day battery, and faster than most pro laptops.",
    description:
      "The MacBook Air 13 with the M4 chip is the default laptop recommendation for almost everyone. It is completely silent, lasts up to 18 hours on a charge, and now drives two external displays with the lid open.",
    highlights: [
      "Apple M4 chip with 10-core GPU",
      "Up to 18 h battery life",
      "Fanless, completely silent design",
      "12MP Center Stage camera",
    ],
    specs: {
      Display: "13.6\" Liquid Retina, 2560x1664, 500 nits",
      Chip: "Apple M4 (10-core CPU, 10-core GPU)",
      RAM: "16 GB unified memory",
      Storage: "256 GB SSD",
      Battery: "Up to 18 h",
      Ports: "2x Thunderbolt 4, MagSafe 3, 3.5 mm jack",
      Weight: "1.24 kg",
    },
    visual: "laptop",
    accent: "#5e8fc7",
  },
  {
    id: "dell-xps-13",
    name: "Dell XPS 13 (9350)",
    brand: "Dell",
    category: "laptops",
    subcategory: "ultrabook",
    price: 1299,
    stock: 11,
    rating: 4.4,
    reviewCount: 463,
    tags: ["dell", "xps", "ultrabook", "lunar-lake", "windows", "portable"],
    blurb: "Dell's iconic ultrabook with Intel Lunar Lake efficiency and an edge-to-edge display.",
    description:
      "The XPS 13 pairs Intel's efficient Core Ultra 7 258V with a near-borderless 13.4-inch display in a machined-aluminium body. Battery life now rivals Apple Silicon, making it one of the best Windows ultraportables.",
    highlights: [
      "Intel Core Ultra 7 258V (Lunar Lake)",
      "Up to 20 h battery life",
      "InfinityEdge 13.4\" display",
      "Premium CNC aluminium build",
    ],
    specs: {
      Display: "13.4\" FHD+ (1920x1200) IPS, 120 Hz",
      CPU: "Intel Core Ultra 7 258V",
      RAM: "16 GB LPDDR5X-8533",
      Storage: "512 GB NVMe SSD",
      Battery: "55 Wh, up to 20 h",
      Ports: "2x Thunderbolt 4",
      Weight: "1.17 kg",
    },
    visual: "laptop",
    accent: "#8d99ae",
  },
  {
    id: "thinkpad-x1-carbon-g12",
    name: "Lenovo ThinkPad X1 Carbon Gen 12",
    brand: "Lenovo",
    category: "laptops",
    subcategory: "business-laptop",
    price: 1749,
    stock: 9,
    rating: 4.6,
    reviewCount: 387,
    tags: ["lenovo", "thinkpad", "business", "ultrabook", "windows", "lightweight"],
    blurb: "The legendary business ultrabook: under a kilo of carbon fibre with the best keyboard around.",
    description:
      "The ThinkPad X1 Carbon Gen 12 remains the gold standard for business laptops. At just 986 grams it disappears in a bag, yet offers a best-in-class keyboard, Core Ultra performance, and full enterprise security.",
    highlights: [
      "Just 986 g in carbon fibre",
      "Legendary ThinkPad keyboard",
      "Intel Core Ultra 7 155U with vPro",
      "MIL-SPEC durability tested",
    ],
    specs: {
      Display: "14\" WUXGA (1920x1200) IPS, 400 nits",
      CPU: "Intel Core Ultra 7 155U",
      RAM: "32 GB LPDDR5X",
      Storage: "1 TB NVMe SSD",
      Battery: "57 Wh, rapid charge",
      Ports: "2x Thunderbolt 4, 2x USB-A, HDMI 2.1",
      Weight: "0.99 kg",
    },
    visual: "laptop",
    accent: "#cc2229",
  },
  {
    id: "zenbook-14-oled",
    name: "ASUS Zenbook 14 OLED",
    brand: "ASUS",
    category: "laptops",
    subcategory: "ultrabook",
    price: 999,
    originalPrice: 1199,
    stock: 19,
    rating: 4.5,
    reviewCount: 542,
    tags: ["asus", "zenbook", "oled", "ultrabook", "windows", "portable"],
    blurb: "A gorgeous 3K OLED display and all-day battery in a slim 1.2 kg chassis — now on sale.",
    description:
      "The Zenbook 14 OLED proves you do not need to spend flagship money for a stunning display. Its 3K 120 Hz OLED panel is paired with an Intel Core Ultra 7 and a 75 Wh battery that easily lasts a full workday.",
    highlights: [
      "14\" 3K OLED, 120 Hz, 100% DCI-P3",
      "Intel Core Ultra 7 155H",
      "75 Wh battery, up to 15 h",
      "Slim 1.2 kg aluminium design",
    ],
    specs: {
      Display: "14\" 3K (2880x1800) OLED, 120 Hz",
      CPU: "Intel Core Ultra 7 155H",
      RAM: "16 GB LPDDR5X",
      Storage: "1 TB NVMe SSD",
      Battery: "75 Wh, up to 15 h",
      Ports: "2x Thunderbolt 4, USB-A, HDMI 2.1",
      Weight: "1.2 kg",
    },
    visual: "laptop",
    accent: "#4a6fa5",
  },

  // -------------------------------------------------------------- desktops
  {
    id: "nzxt-player-three",
    name: "NZXT Player: Three (RTX 5080)",
    brand: "NZXT",
    category: "desktops",
    subcategory: "gaming-desktop",
    price: 2799,
    stock: 6,
    rating: 4.7,
    reviewCount: 184,
    tags: ["gaming", "prebuilt", "nzxt", "rtx-5080", "4k", "rgb"],
    blurb: "NZXT's flagship prebuilt: RTX 5080 and Ryzen 7 9800X3D for uncompromised 4K gaming.",
    description:
      "The Player: Three is built for 4K and high-refresh 1440p gaming without compromise. A Ryzen 7 9800X3D and GeForce RTX 5080 sit inside NZXT's clean H7 Flow chassis with a 240mm AIO keeping everything cool.",
    highlights: [
      "GeForce RTX 5080 16 GB",
      "AMD Ryzen 7 9800X3D",
      "32 GB DDR5 + 2 TB NVMe SSD",
      "240mm Kraken liquid cooling",
    ],
    specs: {
      CPU: "AMD Ryzen 7 9800X3D",
      GPU: "NVIDIA GeForce RTX 5080 16 GB",
      RAM: "32 GB DDR5-6000",
      Storage: "2 TB NVMe Gen4 SSD",
      Cooling: "NZXT Kraken 240mm AIO",
      PSU: "850 W 80+ Gold",
      OS: "Windows 11 Home",
    },
    visual: "desktop",
    accent: "#9146ff",
  },
  {
    id: "hp-omen-35l",
    name: "HP Omen 35L (RTX 5070)",
    brand: "HP",
    category: "desktops",
    subcategory: "gaming-desktop",
    price: 1899,
    originalPrice: 2199,
    stock: 8,
    rating: 4.5,
    reviewCount: 226,
    tags: ["gaming", "prebuilt", "hp", "omen", "rtx-5070", "rgb"],
    blurb: "A high-refresh 1440p machine with the new RTX 5070 — currently on sale.",
    description:
      "The Omen 35L delivers next-gen RTX 5070 performance in a tool-less, upgrade-friendly chassis. With a Core i7-14700F and 32 GB of DDR5, it chews through 1440p ultra settings and streams without breaking a sweat.",
    highlights: [
      "GeForce RTX 5070 12 GB",
      "Intel Core i7-14700F",
      "Tool-less, standard-parts chassis",
      "Omen Light Studio RGB",
    ],
    specs: {
      CPU: "Intel Core i7-14700F",
      GPU: "NVIDIA GeForce RTX 5070 12 GB",
      RAM: "32 GB DDR5-5600",
      Storage: "1 TB NVMe Gen4 SSD",
      Cooling: "120mm liquid cooler",
      PSU: "800 W 80+ Gold",
      OS: "Windows 11 Home",
    },
    visual: "desktop",
    accent: "#c2185b",
  },
  {
    id: "legion-tower-5",
    name: "Lenovo Legion Tower 5 (RTX 4070 Super)",
    brand: "Lenovo",
    category: "desktops",
    subcategory: "gaming-desktop",
    price: 1499,
    stock: 10,
    rating: 4.5,
    reviewCount: 312,
    tags: ["gaming", "prebuilt", "lenovo", "legion", "rtx-4070-super"],
    blurb: "A balanced 1440p gaming tower with the RTX 4070 Super and Ryzen 7 7700.",
    description:
      "The Legion Tower 5 hits the value sweet spot for 1440p gaming. The RTX 4070 Super and Ryzen 7 7700 combo handles every modern title at high refresh rates, and the case leaves plenty of room for future upgrades.",
    highlights: [
      "GeForce RTX 4070 Super 12 GB",
      "AMD Ryzen 7 7700",
      "Standard ATX parts, easy upgrades",
      "Quiet air cooling out of the box",
    ],
    specs: {
      CPU: "AMD Ryzen 7 7700",
      GPU: "NVIDIA GeForce RTX 4070 Super 12 GB",
      RAM: "32 GB DDR5-5600",
      Storage: "1 TB NVMe Gen4 SSD",
      Cooling: "Air cooler with 2 case fans",
      PSU: "650 W 80+ Gold",
      OS: "Windows 11 Home",
    },
    visual: "desktop",
    accent: "#2e5db3",
  },
  {
    id: "msi-codex-r2",
    name: "MSI Codex R2 (RTX 4060)",
    brand: "MSI",
    category: "desktops",
    subcategory: "gaming-desktop",
    price: 999,
    stock: 15,
    rating: 4.3,
    reviewCount: 198,
    tags: ["gaming", "prebuilt", "msi", "rtx-4060", "budget", "1080p"],
    blurb: "The smart entry into PC gaming: RTX 4060 power at a console-friendly price.",
    description:
      "The MSI Codex R2 makes 1080p PC gaming affordable. The RTX 4060 with DLSS 3 frame generation pushes high frame rates in esports and AAA titles alike, all from a compact, quiet mid-tower.",
    highlights: [
      "GeForce RTX 4060 8 GB with DLSS 3",
      "Intel Core i5-14400F",
      "16 GB DDR5, 1 TB SSD",
      "Compact, quiet mid-tower",
    ],
    specs: {
      CPU: "Intel Core i5-14400F",
      GPU: "NVIDIA GeForce RTX 4060 8 GB",
      RAM: "16 GB DDR5-5200",
      Storage: "1 TB NVMe SSD",
      Cooling: "Air cooler with RGB fan",
      PSU: "550 W 80+ Bronze",
      OS: "Windows 11 Home",
    },
    visual: "desktop",
    accent: "#d4202c",
  },

  // ------------------------------------------------------------ components
  // CPUs
  {
    id: "ryzen-7-9800x3d",
    name: "AMD Ryzen 7 9800X3D",
    brand: "AMD",
    category: "components",
    subcategory: "cpu",
    price: 529,
    stock: 17,
    rating: 4.9,
    reviewCount: 1245,
    tags: ["cpu", "amd", "ryzen", "am5", "gaming", "x3d", "ddr5"],
    blurb: "The fastest gaming CPU on the planet, thanks to second-gen 3D V-Cache.",
    description:
      "The Ryzen 7 9800X3D is the undisputed gaming CPU champion. Second-generation 3D V-Cache stacks 96 MB of L3 underneath the cores, and unlike earlier X3D chips it is fully overclockable.",
    highlights: [
      "Best-in-class gaming performance",
      "96 MB L3 with 2nd-gen 3D V-Cache",
      "8 cores / 16 threads, Zen 5",
      "Fully unlocked for overclocking",
    ],
    specs: {
      Socket: "AM5",
      "Cores / Threads": "8 / 16",
      "Boost clock": "Up to 5.2 GHz",
      Cache: "96 MB L3 (3D V-Cache)",
      Memory: "DDR5-5600 (dual channel)",
      TDP: "120 W",
      Architecture: "Zen 5",
    },
    compat: {
      socket: "AM5",
      memoryType: "DDR5",
      drawWatts: 120,
    },
    visual: "cpu",
    accent: "#ed1c24",
  },
  {
    id: "ryzen-7-7800x3d",
    name: "AMD Ryzen 7 7800X3D",
    brand: "AMD",
    category: "components",
    subcategory: "cpu",
    price: 349,
    originalPrice: 429,
    stock: 21,
    rating: 4.9,
    reviewCount: 3187,
    tags: ["cpu", "amd", "ryzen", "am5", "gaming", "x3d", "ddr5"],
    blurb: "The previous gaming king at a serious discount — still phenomenal in every title.",
    description:
      "The Ryzen 7 7800X3D dominated gaming benchmarks for two years, and at this sale price it is arguably better value than its successor. 96 MB of 3D V-Cache and excellent efficiency make it the smart pick for pure gaming builds.",
    highlights: [
      "96 MB L3 with 3D V-Cache",
      "8 cores / 16 threads, Zen 4",
      "Outstanding power efficiency",
      "Unbeatable price-to-performance on sale",
    ],
    specs: {
      Socket: "AM5",
      "Cores / Threads": "8 / 16",
      "Boost clock": "Up to 5.0 GHz",
      Cache: "96 MB L3 (3D V-Cache)",
      Memory: "DDR5-5200 (dual channel)",
      TDP: "120 W",
      Architecture: "Zen 4",
    },
    compat: {
      socket: "AM5",
      memoryType: "DDR5",
      drawWatts: 120,
    },
    visual: "cpu",
    accent: "#ed1c24",
  },
  {
    id: "ryzen-5-7600",
    name: "AMD Ryzen 5 7600",
    brand: "AMD",
    category: "components",
    subcategory: "cpu",
    price: 199,
    stock: 33,
    rating: 4.7,
    reviewCount: 1456,
    tags: ["cpu", "amd", "ryzen", "am5", "gaming", "budget", "ddr5"],
    blurb: "The go-to budget AM5 chip: six fast Zen 4 cores with a cooler in the box.",
    description:
      "The Ryzen 5 7600 is the foundation of countless great-value gaming builds. Six Zen 4 cores boost to 5.1 GHz, the bundled Wraith Stealth cooler works fine at stock, and the AM5 platform gives you a clear upgrade path.",
    highlights: [
      "6 cores / 12 threads, Zen 4",
      "Wraith Stealth cooler included",
      "Efficient 65 W TDP",
      "AM5 upgrade path to X3D chips",
    ],
    specs: {
      Socket: "AM5",
      "Cores / Threads": "6 / 12",
      "Boost clock": "Up to 5.1 GHz",
      Cache: "32 MB L3",
      Memory: "DDR5-5200 (dual channel)",
      TDP: "65 W",
      Cooler: "Wraith Stealth included",
    },
    compat: {
      socket: "AM5",
      memoryType: "DDR5",
      drawWatts: 65,
    },
    visual: "cpu",
    accent: "#f26522",
  },
  {
    id: "core-i7-14700k",
    name: "Intel Core i7-14700K",
    brand: "Intel",
    category: "components",
    subcategory: "cpu",
    price: 389,
    stock: 14,
    rating: 4.6,
    reviewCount: 982,
    tags: ["cpu", "intel", "core-i7", "lga1700", "gaming", "ddr5", "overclocking"],
    blurb: "20 cores of hybrid muscle for gamers who also stream, edit, and compile.",
    description:
      "The Core i7-14700K blends 8 performance cores with 12 efficiency cores for a total of 28 threads. It games nearly as fast as anything on the market while crushing productivity workloads that lighter chips choke on.",
    highlights: [
      "20 cores (8P + 12E) / 28 threads",
      "Boosts up to 5.6 GHz",
      "Unlocked for overclocking",
      "Strong multi-threaded productivity",
    ],
    specs: {
      Socket: "LGA1700",
      "Cores / Threads": "20 (8P + 12E) / 28",
      "Boost clock": "Up to 5.6 GHz",
      Cache: "33 MB L3",
      Memory: "DDR5-5600 / DDR4-3200",
      TDP: "125 W base / 253 W max turbo",
      Graphics: "Intel UHD 770",
    },
    compat: {
      socket: "LGA1700",
      memoryType: "DDR5",
      drawWatts: 125,
    },
    visual: "cpu",
    accent: "#0068b5",
  },
  {
    id: "core-i5-14600k",
    name: "Intel Core i5-14600K",
    brand: "Intel",
    category: "components",
    subcategory: "cpu",
    price: 279,
    stock: 26,
    rating: 4.7,
    reviewCount: 1134,
    tags: ["cpu", "intel", "core-i5", "lga1700", "gaming", "ddr5", "overclocking"],
    blurb: "The mid-range Intel favourite: 14 cores that game and multitask far above their price.",
    description:
      "The Core i5-14600K has long been the default mid-range recommendation for Intel builds. With 14 cores boosting to 5.3 GHz, it games within a few percent of much pricier chips and handles streaming on the side.",
    highlights: [
      "14 cores (6P + 8E) / 20 threads",
      "Boosts up to 5.3 GHz",
      "Excellent gaming value",
      "Unlocked multiplier",
    ],
    specs: {
      Socket: "LGA1700",
      "Cores / Threads": "14 (6P + 8E) / 20",
      "Boost clock": "Up to 5.3 GHz",
      Cache: "24 MB L3",
      Memory: "DDR5-5600 / DDR4-3200",
      TDP: "125 W base / 181 W max turbo",
      Graphics: "Intel UHD 770",
    },
    compat: {
      socket: "LGA1700",
      memoryType: "DDR5",
      drawWatts: 125,
    },
    visual: "cpu",
    accent: "#0068b5",
  },
  // Motherboards
  {
    id: "asus-rog-strix-x870-a",
    name: "ASUS ROG Strix X870-A Gaming WiFi",
    brand: "ASUS",
    category: "components",
    subcategory: "motherboard",
    price: 329,
    stock: 11,
    rating: 4.6,
    reviewCount: 287,
    tags: ["motherboard", "asus", "rog", "am5", "x870", "ddr5", "gaming", "wifi-7"],
    blurb: "A premium AM5 board with PCIe 5.0, Wi-Fi 7, and USB4 for high-end Ryzen builds.",
    description:
      "The ROG Strix X870-A is the board to pair with a 9800X3D. PCIe 5.0 for GPU and SSD, USB4, Wi-Fi 7, and robust 16+2+2 power stages give your build modern connectivity and overclocking headroom.",
    highlights: [
      "PCIe 5.0 x16 and Gen5 M.2",
      "Wi-Fi 7 and USB4 onboard",
      "16+2+2 power stages",
      "Q-Release slot and tool-less M.2",
    ],
    specs: {
      Socket: "AM5",
      Chipset: "AMD X870",
      "Form factor": "ATX",
      Memory: "4x DIMM, DDR5 up to 8000+ MT/s",
      "M.2 slots": "4 (1x Gen5)",
      Networking: "Wi-Fi 7, 2.5 GbE",
      "Rear USB": "USB4, USB 3.2 Gen 2x2",
    },
    compat: {
      socket: "AM5",
      memoryType: "DDR5",
    },
    visual: "motherboard",
    accent: "#b8b8c0",
  },
  {
    id: "msi-b650-tomahawk",
    name: "MSI MAG B650 Tomahawk WiFi",
    brand: "MSI",
    category: "components",
    subcategory: "motherboard",
    price: 199,
    stock: 23,
    rating: 4.7,
    reviewCount: 864,
    tags: ["motherboard", "msi", "am5", "b650", "ddr5", "gaming", "wifi"],
    blurb: "The value AM5 favourite: rock-solid VRMs and full features without the X-series price.",
    description:
      "The B650 Tomahawk WiFi is the mainstream AM5 board everyone recommends. Its 14+2+1 VRM happily runs any Ryzen chip including X3D parts, and you get Wi-Fi 6E, 2.5 GbE, and three M.2 slots.",
    highlights: [
      "Runs every AM5 CPU incl. X3D",
      "14+2+1 duet rail power design",
      "Wi-Fi 6E and 2.5 GbE",
      "3x M.2 with shields",
    ],
    specs: {
      Socket: "AM5",
      Chipset: "AMD B650",
      "Form factor": "ATX",
      Memory: "4x DIMM, DDR5 up to 6400+ MT/s",
      "M.2 slots": "3 (Gen4)",
      Networking: "Wi-Fi 6E, 2.5 GbE",
      "Rear USB": "USB 3.2 Gen 2x2 Type-C",
    },
    compat: {
      socket: "AM5",
      memoryType: "DDR5",
    },
    visual: "motherboard",
    accent: "#54585a",
  },
  {
    id: "msi-z790-tomahawk",
    name: "MSI MAG Z790 Tomahawk WiFi",
    brand: "MSI",
    category: "components",
    subcategory: "motherboard",
    price: 249,
    stock: 13,
    rating: 4.6,
    reviewCount: 512,
    tags: ["motherboard", "msi", "lga1700", "z790", "ddr5", "gaming", "wifi"],
    blurb: "A dependable Z790 DDR5 board for 14th-gen Intel overclocking builds.",
    description:
      "The Z790 Tomahawk WiFi gives 13th and 14th-gen Intel chips a stable, overclock-ready home. Strong 16+1+1 VRMs, DDR5 support up to 7800 MT/s, and four M.2 slots cover everything a high-end Intel build needs.",
    highlights: [
      "Supports Intel 12th–14th gen",
      "16+1+1 power phases for OC",
      "DDR5 up to 7800+ MT/s",
      "4x M.2 Gen4 slots",
    ],
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel Z790",
      "Form factor": "ATX",
      Memory: "4x DIMM, DDR5 up to 7800+ MT/s",
      "M.2 slots": "4 (Gen4)",
      Networking: "Wi-Fi 6E, 2.5 GbE",
      "Rear USB": "USB 3.2 Gen 2x2 Type-C",
    },
    compat: {
      socket: "LGA1700",
      memoryType: "DDR5",
    },
    visual: "motherboard",
    accent: "#54585a",
  },
  {
    id: "asrock-b760m-pro-rs",
    name: "ASRock B760M Pro RS (DDR4)",
    brand: "ASRock",
    category: "components",
    subcategory: "motherboard",
    price: 119,
    stock: 29,
    rating: 4.4,
    reviewCount: 376,
    tags: ["motherboard", "asrock", "lga1700", "b760", "ddr4", "budget", "micro-atx"],
    blurb: "A budget LGA1700 micro-ATX board that reuses affordable DDR4 memory.",
    description:
      "The B760M Pro RS keeps Intel build costs down by sticking with DDR4 memory, which remains noticeably cheaper than DDR5. It supports 12th to 14th-gen Core chips and includes two Gen4 M.2 slots — just remember it will not accept DDR5 kits.",
    highlights: [
      "Budget-friendly DDR4 platform",
      "Supports Intel 12th–14th gen",
      "2x M.2 Gen4 slots",
      "Compact micro-ATX form factor",
    ],
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel B760",
      "Form factor": "Micro-ATX",
      Memory: "4x DIMM, DDR4 up to 5333+ MT/s (no DDR5)",
      "M.2 slots": "2 (Gen4)",
      Networking: "1 GbE",
      "Rear USB": "USB 3.2 Gen 1 Type-C",
    },
    compat: {
      socket: "LGA1700",
      memoryType: "DDR4",
    },
    visual: "motherboard",
    accent: "#0a9b4b",
  },
  // GPUs
  {
    id: "rtx-5090",
    name: "ASUS ROG Astral GeForce RTX 5090 32GB",
    brand: "ASUS",
    category: "components",
    subcategory: "gpu",
    price: 2899,
    stock: 2,
    rating: 4.8,
    reviewCount: 156,
    tags: ["gpu", "nvidia", "rtx-5090", "blackwell", "gaming", "flagship", "4k", "dlss4", "ray-tracing"],
    blurb: "The uncompromising Blackwell flagship — 32 GB of GDDR7 for 4K and beyond. Only 2 left.",
    description:
      "The ROG Astral RTX 5090 is as fast as consumer graphics gets, with 32 GB of GDDR7 on NVIDIA's top Blackwell die and DLSS 4 Multi Frame Generation. It pulls up to 575 W and stretches 358 mm long, so check your case clearance and power supply before you buy — this card demands a serious build around it.",
    highlights: [
      "32 GB GDDR7 on the Blackwell flagship die",
      "DLSS 4 with Multi Frame Generation",
      "Quad-fan ROG Astral cooler",
      "Built for 4K max settings and high-refresh",
    ],
    specs: {
      GPU: "NVIDIA GeForce RTX 5090",
      Memory: "32 GB GDDR7, 512-bit",
      "Boost clock": "2610 MHz (OC mode)",
      "Power draw": "575 W",
      "Power connector": "1x 16-pin (12V-2x6), 600 W",
      Length: "358 mm (3.8 slots)",
      Outputs: "3x DisplayPort 2.1b, 2x HDMI 2.1b",
    },
    compat: {
      drawWatts: 575,
      gpuLengthMm: 358,
    },
    visual: "gpu",
    accent: "#76b900",
  },
  {
    id: "rtx-5080",
    name: "ASUS TUF GeForce RTX 5080 16GB",
    brand: "ASUS",
    category: "components",
    subcategory: "gpu",
    price: 1249,
    stock: 7,
    rating: 4.7,
    reviewCount: 438,
    tags: ["gpu", "nvidia", "rtx-5080", "blackwell", "gaming", "4k", "dlss4", "ray-tracing"],
    blurb: "Blackwell-class 4K gaming with DLSS 4 Multi Frame Generation in ASUS's tank-like TUF cooler.",
    description:
      "The TUF GeForce RTX 5080 brings NVIDIA's Blackwell architecture and DLSS 4 to no-compromise 4K gaming. ASUS's triple-fan TUF cooler keeps the 360 W card cool and quiet, with a metal frame built for years of service.",
    highlights: [
      "16 GB GDDR7 on Blackwell architecture",
      "DLSS 4 with Multi Frame Generation",
      "Beefy triple-fan TUF cooling",
      "Native 4K high-refresh performance",
    ],
    specs: {
      GPU: "NVIDIA GeForce RTX 5080",
      Memory: "16 GB GDDR7, 256-bit",
      "Boost clock": "2640 MHz (OC mode)",
      "Power draw": "360 W",
      "Power connector": "1x 16-pin (12V-2x6)",
      Length: "304 mm (3.6 slots)",
      Outputs: "3x DisplayPort 2.1b, 2x HDMI 2.1b",
    },
    compat: {
      drawWatts: 360,
      gpuLengthMm: 304,
    },
    visual: "gpu",
    accent: "#76b900",
  },
  {
    id: "rtx-5070",
    name: "MSI Ventus GeForce RTX 5070 12GB",
    brand: "MSI",
    category: "components",
    subcategory: "gpu",
    price: 649,
    stock: 0,
    rating: 4.6,
    reviewCount: 367,
    tags: ["gpu", "nvidia", "rtx-5070", "blackwell", "gaming", "1440p", "dlss4", "ray-tracing"],
    blurb: "The 1440p Blackwell sweet spot with DLSS 4 — selling out as fast as it arrives.",
    description:
      "The RTX 5070 hits the classic x70-class sweet spot: outstanding 1440p performance with DLSS 4 Multi Frame Generation for headroom well into 4K. MSI's compact Ventus cooler makes it an easy fit in most cases.",
    highlights: [
      "12 GB GDDR7 on Blackwell architecture",
      "DLSS 4 Multi Frame Generation",
      "Compact dual-slot design",
      "Excellent 1440p price-to-performance",
    ],
    specs: {
      GPU: "NVIDIA GeForce RTX 5070",
      Memory: "12 GB GDDR7, 192-bit",
      "Boost clock": "2512 MHz",
      "Power draw": "250 W",
      "Power connector": "1x 16-pin (12V-2x6)",
      Length: "232 mm (2 slots)",
      Outputs: "3x DisplayPort 2.1b, 1x HDMI 2.1b",
    },
    compat: {
      drawWatts: 250,
      gpuLengthMm: 232,
    },
    visual: "gpu",
    accent: "#76b900",
  },
  {
    id: "rx-9070-xt",
    name: "Sapphire Pulse Radeon RX 9070 XT 16GB",
    brand: "Sapphire",
    category: "components",
    subcategory: "gpu",
    price: 689,
    stock: 12,
    rating: 4.7,
    reviewCount: 294,
    tags: ["gpu", "amd", "radeon", "rx-9070-xt", "rdna4", "gaming", "1440p", "4k", "fsr4"],
    blurb: "AMD's RDNA 4 challenger: RTX 5070-beating performance with 16 GB of VRAM.",
    description:
      "The RX 9070 XT is AMD's strongest GPU value in years, trading blows with cards far above its price at 1440p and 4K. RDNA 4 brings vastly improved ray tracing and FSR 4 machine-learning upscaling, plus a roomy 16 GB of VRAM.",
    highlights: [
      "16 GB GDDR6 — plenty for 4K textures",
      "FSR 4 ML upscaling",
      "Big ray tracing uplift over RDNA 3",
      "Quiet Sapphire Pulse dual-BIOS cooler",
    ],
    specs: {
      GPU: "AMD Radeon RX 9070 XT",
      Memory: "16 GB GDDR6, 256-bit",
      "Boost clock": "2970 MHz",
      "Power draw": "304 W",
      "Power connector": "2x 8-pin",
      Length: "287 mm (2.5 slots)",
      Outputs: "2x DisplayPort 2.1a, 2x HDMI 2.1b",
    },
    compat: {
      drawWatts: 304,
      gpuLengthMm: 287,
    },
    visual: "gpu",
    accent: "#ed1c24",
  },
  {
    id: "rtx-5060-ti",
    name: "Gigabyte Windforce GeForce RTX 5060 Ti 16GB",
    brand: "Gigabyte",
    category: "components",
    subcategory: "gpu",
    price: 479,
    stock: 19,
    rating: 4.4,
    reviewCount: 213,
    tags: ["gpu", "nvidia", "rtx-5060-ti", "blackwell", "gaming", "1440p", "dlss4"],
    blurb: "16 GB of VRAM and DLSS 4 make this the future-proof mid-range pick.",
    description:
      "The RTX 5060 Ti 16GB is the mid-range card to buy if you keep GPUs for years — its 16 GB buffer will not run out of VRAM in modern titles. DLSS 4 frame generation lifts it comfortably into high-refresh 1440p territory.",
    highlights: [
      "16 GB GDDR7 — no VRAM compromises",
      "DLSS 4 Multi Frame Generation",
      "Efficient 180 W power draw",
      "Cool and quiet Windforce cooler",
    ],
    specs: {
      GPU: "NVIDIA GeForce RTX 5060 Ti",
      Memory: "16 GB GDDR7, 128-bit",
      "Boost clock": "2572 MHz",
      "Power draw": "180 W",
      "Power connector": "1x 8-pin",
      Length: "244 mm (2 slots)",
      Outputs: "3x DisplayPort 2.1b, 1x HDMI 2.1b",
    },
    compat: {
      drawWatts: 180,
      gpuLengthMm: 244,
    },
    visual: "gpu",
    accent: "#76b900",
  },
  {
    id: "rtx-4060",
    name: "MSI Ventus GeForce RTX 4060 8GB",
    brand: "MSI",
    category: "components",
    subcategory: "gpu",
    price: 269,
    originalPrice: 319,
    stock: 34,
    rating: 4.5,
    reviewCount: 1672,
    tags: ["gpu", "nvidia", "rtx-4060", "ada", "gaming", "1080p", "dlss3", "budget"],
    blurb: "The efficient 1080p workhorse with DLSS 3 — now at clearance pricing.",
    description:
      "The RTX 4060 remains the easiest recommendation for 1080p gaming, sipping just 115 W while DLSS 3 frame generation keeps frame rates high. At its sale price, it is the perfect drop-in upgrade for older systems with modest power supplies.",
    highlights: [
      "Excellent 1080p performance",
      "DLSS 3 frame generation",
      "Only 115 W — works with most PSUs",
      "Compact 240 mm dual-fan design",
    ],
    specs: {
      GPU: "NVIDIA GeForce RTX 4060",
      Memory: "8 GB GDDR6, 128-bit",
      "Boost clock": "2490 MHz",
      "Power draw": "115 W",
      "Power connector": "1x 8-pin",
      Length: "240 mm (2 slots)",
      Outputs: "3x DisplayPort 1.4a, 1x HDMI 2.1",
    },
    compat: {
      drawWatts: 115,
      gpuLengthMm: 240,
    },
    visual: "gpu",
    accent: "#76b900",
  },
  // RAM
  {
    id: "corsair-vengeance-32gb-ddr5",
    name: "Corsair Vengeance 32GB (2x16GB) DDR5-6000 CL30",
    brand: "Corsair",
    category: "components",
    subcategory: "ram",
    price: 119,
    stock: 41,
    rating: 4.8,
    reviewCount: 2034,
    tags: ["ram", "corsair", "ddr5", "32gb", "6000mhz", "gaming", "expo"],
    blurb: "The DDR5 sweet-spot kit: 6000 MT/s CL30 with AMD EXPO and Intel XMP profiles.",
    description:
      "This Corsair Vengeance kit hits the ideal DDR5 spec for Ryzen 7000/9000 builds: 6000 MT/s at a tight CL30. One-click EXPO and XMP profiles get you to rated speed instantly, and the low-profile heatspreader clears every cooler.",
    highlights: [
      "DDR5-6000 CL30 — the Ryzen sweet spot",
      "AMD EXPO and Intel XMP 3.0",
      "Low-profile design fits under big coolers",
      "Lifetime warranty",
    ],
    specs: {
      Capacity: "32 GB (2x 16 GB)",
      Type: "DDR5",
      Speed: "6000 MT/s",
      Latency: "CL30-36-36-76",
      Voltage: "1.40 V",
      Profiles: "AMD EXPO, Intel XMP 3.0",
      Height: "34.9 mm",
    },
    compat: {
      memoryType: "DDR5",
    },
    visual: "ram",
    accent: "#1a1a1a",
  },
  {
    id: "kingston-fury-beast-16gb-ddr4",
    name: "Kingston Fury Beast 16GB (2x8GB) DDR4-3200 CL16",
    brand: "Kingston",
    category: "components",
    subcategory: "ram",
    price: 45,
    stock: 56,
    rating: 4.7,
    reviewCount: 1893,
    tags: ["ram", "kingston", "ddr4", "16gb", "3200mhz", "budget", "xmp"],
    blurb: "Reliable, affordable DDR4 for budget builds and older-platform upgrades.",
    description:
      "The Fury Beast DDR4-3200 kit is the dependable choice for budget Intel boards and AM4 systems. Plug-and-play XMP gets you to 3200 MT/s, and the low-profile heatspreaders fit anywhere. Note this is DDR4 — it will not work in DDR5-only boards.",
    highlights: [
      "Plug-and-play XMP at 3200 MT/s",
      "Low-profile 34.1 mm heatspreader",
      "Great value for DDR4 platforms",
      "Lifetime warranty",
    ],
    specs: {
      Capacity: "16 GB (2x 8 GB)",
      Type: "DDR4",
      Speed: "3200 MT/s",
      Latency: "CL16-18-18",
      Voltage: "1.35 V",
      Profiles: "Intel XMP 2.0",
      Height: "34.1 mm",
    },
    compat: {
      memoryType: "DDR4",
    },
    visual: "ram",
    accent: "#c8102e",
  },
  // Storage
  {
    id: "samsung-990-pro-2tb",
    name: "Samsung 990 Pro 2TB NVMe SSD",
    brand: "Samsung",
    category: "components",
    subcategory: "ssd",
    price: 159,
    originalPrice: 199,
    stock: 37,
    rating: 4.9,
    reviewCount: 2811,
    tags: ["storage", "ssd", "nvme", "samsung", "2tb", "gen4", "gaming"],
    blurb: "The benchmark Gen4 NVMe drive — 7450 MB/s and class-leading endurance, on sale.",
    description:
      "The Samsung 990 Pro remains the gold standard for PCIe 4.0 SSDs, saturating the interface at 7450 MB/s reads. Its in-house controller and TLC NAND deliver consistent performance with excellent thermals and a 5-year warranty.",
    highlights: [
      "7450 MB/s read, 6900 MB/s write",
      "2 TB of fast TLC NAND",
      "Up to 1200 TBW endurance",
      "5-year warranty",
    ],
    specs: {
      Capacity: "2 TB",
      Interface: "PCIe 4.0 x4, NVMe 2.0",
      "Form factor": "M.2 2280",
      "Sequential read": "7450 MB/s",
      "Sequential write": "6900 MB/s",
      Endurance: "1200 TBW",
      Warranty: "5 years",
    },
    visual: "storage",
    accent: "#1428a0",
  },
  {
    id: "wd-black-sn770-1tb",
    name: "WD Black SN770 1TB NVMe SSD",
    brand: "Western Digital",
    category: "components",
    subcategory: "ssd",
    price: 69,
    stock: 48,
    rating: 4.7,
    reviewCount: 1547,
    tags: ["storage", "ssd", "nvme", "wd", "1tb", "gen4", "gaming", "budget"],
    blurb: "The budget gamer's favourite NVMe: Gen4 speeds at an entry-level price.",
    description:
      "The WD Black SN770 punches well above its price with 5150 MB/s reads and snappy real-world performance. Its DRAM-less design keeps costs down without hurting gaming load times, making it the ideal second drive or budget boot disk.",
    highlights: [
      "5150 MB/s read speeds",
      "Great real-world gaming performance",
      "Runs cool without a heatsink",
      "5-year warranty",
    ],
    specs: {
      Capacity: "1 TB",
      Interface: "PCIe 4.0 x4, NVMe",
      "Form factor": "M.2 2280",
      "Sequential read": "5150 MB/s",
      "Sequential write": "4900 MB/s",
      Endurance: "600 TBW",
      Warranty: "5 years",
    },
    visual: "storage",
    accent: "#1c1c1c",
  },
  // PSUs
  {
    id: "corsair-rm850e",
    name: "Corsair RM850e 850W 80+ Gold",
    brand: "Corsair",
    category: "components",
    subcategory: "psu",
    price: 119,
    stock: 25,
    rating: 4.8,
    reviewCount: 1322,
    tags: ["psu", "corsair", "850w", "gold", "modular", "atx3", "gaming"],
    blurb: "850 W of fully modular Gold-rated power with a native 12V-2x6 GPU cable.",
    description:
      "The RM850e is the go-to PSU for high-end GPU builds. ATX 3.1 compliance and a native 12V-2x6 connector power an RTX 5080 with a single cable, while the quiet 120 mm fan stays off entirely at low loads.",
    highlights: [
      "ATX 3.1 with native 12V-2x6 cable",
      "Fully modular, 80+ Gold efficiency",
      "Zero-RPM fan mode",
      "7-year warranty",
    ],
    specs: {
      Wattage: "850 W",
      Efficiency: "80+ Gold / Cybenetics Gold",
      Modularity: "Fully modular",
      "GPU connector": "1x 12V-2x6 (600 W), 3x PCIe 8-pin",
      "ATX standard": "ATX 3.1",
      Fan: "120 mm, zero-RPM mode",
      Warranty: "7 years",
    },
    compat: {
      psuWatts: 850,
    },
    visual: "psu",
    accent: "#ffd200",
  },
  {
    id: "bequiet-pure-power-12m-650",
    name: "be quiet! Pure Power 12 M 650W",
    brand: "be quiet!",
    category: "components",
    subcategory: "psu",
    price: 89,
    stock: 31,
    rating: 4.7,
    reviewCount: 768,
    tags: ["psu", "be-quiet", "650w", "gold", "modular", "atx3", "silent"],
    blurb: "Whisper-quiet 650 W Gold power — ideal for mid-range builds and efficient GPUs.",
    description:
      "The Pure Power 12 M delivers be quiet!'s signature silence with full modularity and 80+ Gold efficiency. 650 W comfortably feeds mid-range systems up to an RTX 5070-class card, though power-hungry flagship GPUs will want more headroom.",
    highlights: [
      "Near-silent 120 mm fan",
      "Fully modular, ATX 3.1 ready",
      "Includes 12V-2x6 GPU cable",
      "10-year warranty",
    ],
    specs: {
      Wattage: "650 W",
      Efficiency: "80+ Gold",
      Modularity: "Fully modular",
      "GPU connector": "1x 12V-2x6 (300 W), 2x PCIe 8-pin",
      "ATX standard": "ATX 3.1",
      Fan: "120 mm silence-optimised",
      Warranty: "10 years",
    },
    compat: {
      psuWatts: 650,
    },
    visual: "psu",
    accent: "#f47b20",
  },
  // Cases
  {
    id: "nzxt-h5-flow",
    name: "NZXT H5 Flow",
    brand: "NZXT",
    category: "components",
    subcategory: "case",
    price: 99,
    stock: 18,
    rating: 4.6,
    reviewCount: 932,
    tags: ["case", "nzxt", "atx", "airflow", "mid-tower", "gaming", "white"],
    blurb: "NZXT's clean mid-tower with a perforated front and room for the biggest GPUs.",
    description:
      "The H5 Flow pairs NZXT's minimalist looks with a high-airflow perforated front panel. It swallows GPUs up to 365 mm, supports 280 mm radiators up top, and keeps cable management painless with a wide rear channel.",
    highlights: [
      "Fits GPUs up to 365 mm",
      "High-airflow perforated front",
      "Tool-less tempered glass panel",
      "Clean cable management channels",
    ],
    specs: {
      "Form factor": "ATX mid-tower",
      "Motherboard support": "Mini-ITX to ATX",
      "Max GPU length": "365 mm",
      "Radiator support": "Up to 280 mm front / 240 mm top",
      "Included fans": "2x 120 mm",
      "Drive bays": "2x 2.5\", 1x 3.5\"",
      Dimensions: "446 x 227 x 464 mm",
    },
    compat: {
      maxGpuLengthMm: 365,
    },
    visual: "case",
    accent: "#9146ff",
  },
  {
    id: "fractal-terra-itx",
    name: "Fractal Design Terra (Mini-ITX)",
    brand: "Fractal Design",
    category: "components",
    subcategory: "case",
    price: 179,
    stock: 9,
    rating: 4.5,
    reviewCount: 411,
    tags: ["case", "fractal", "itx", "sff", "compact", "aluminium", "small-form-factor"],
    blurb: "A gorgeous 10.4-litre aluminium ITX case — check your GPU length before you buy.",
    description:
      "The Terra is one of the most beautiful small-form-factor cases ever made, wrapped in anodised aluminium with a walnut accent. At 10.4 litres it demands careful part selection: GPUs longer than 280 mm will not fit.",
    highlights: [
      "Stunning anodised aluminium + walnut",
      "Just 10.4 litres of volume",
      "Adjustable spine for GPU/cooler balance",
      "Fits GPUs up to 280 mm",
    ],
    specs: {
      "Form factor": "Mini-ITX",
      "Motherboard support": "Mini-ITX only",
      "Max GPU length": "280 mm (3-slot max)",
      "CPU cooler height": "Up to 77 mm",
      PSU: "SFX / SFX-L",
      "Drive bays": "2x 2.5\"",
      Dimensions: "343 x 153 x 218 mm (10.4 L)",
    },
    compat: {
      maxGpuLengthMm: 280,
    },
    visual: "case",
    accent: "#3d6b50",
  },

  // -------------------------------------------------------------- monitors
  {
    id: "lg-ultragear-27gs75q",
    name: "LG UltraGear 27GS75Q",
    brand: "LG",
    category: "monitors",
    subcategory: "gaming-monitor",
    price: 249,
    originalPrice: 299,
    stock: 26,
    rating: 4.6,
    reviewCount: 884,
    tags: ["monitor", "gaming", "lg", "ultragear", "1440p", "180hz", "ips", "g-sync"],
    blurb: "The 1440p/180 Hz gaming sweet spot with a fast IPS panel — heavily discounted.",
    description:
      "The UltraGear 27GS75Q nails the specs most gamers actually want: 27 inches, QHD resolution, and a 180 Hz IPS panel with 1 ms response. G-Sync compatibility and FreeSync support keep frames tear-free on any GPU.",
    highlights: [
      "27\" QHD IPS at 180 Hz",
      "1 ms GtG response time",
      "G-Sync Compatible + FreeSync",
      "HDR10 with 99% sRGB",
    ],
    specs: {
      Display: "27\" IPS, 2560x1440",
      "Refresh rate": "180 Hz",
      "Response time": "1 ms GtG",
      "Adaptive sync": "G-Sync Compatible, AMD FreeSync",
      HDR: "HDR10",
      Inputs: "2x HDMI 2.1, 1x DisplayPort 1.4",
      Stand: "Tilt, height adjustable",
    },
    visual: "monitor",
    accent: "#c4174c",
  },
  {
    id: "samsung-odyssey-g7-32",
    name: "Samsung Odyssey G7 32 (4K 144Hz)",
    brand: "Samsung",
    category: "monitors",
    subcategory: "gaming-monitor",
    price: 599,
    stock: 12,
    rating: 4.5,
    reviewCount: 537,
    tags: ["monitor", "gaming", "samsung", "odyssey", "4k", "144hz", "ips", "hdr"],
    blurb: "Big, sharp, and fast: 32 inches of 4K gaming at 144 Hz.",
    description:
      "The Odyssey G7 32 pairs a crisp 4K IPS panel with a 144 Hz refresh rate, making it the natural partner for an RTX 5080-class GPU. HDR10+ support and a 1 ms response time round out a serious big-screen gaming display.",
    highlights: [
      "32\" 4K IPS at 144 Hz",
      "1 ms GtG response time",
      "HDR10+ and FreeSync Premium Pro",
      "Ergonomic height/pivot stand",
    ],
    specs: {
      Display: "32\" IPS, 3840x2160",
      "Refresh rate": "144 Hz",
      "Response time": "1 ms GtG",
      "Adaptive sync": "FreeSync Premium Pro, G-Sync Compatible",
      HDR: "HDR10+, VESA DisplayHDR 400",
      Inputs: "2x HDMI 2.1, 1x DisplayPort 1.4",
      Stand: "Height, tilt, swivel, pivot",
    },
    visual: "monitor",
    accent: "#1f6fd6",
  },
  {
    id: "dell-ultrasharp-u2723qe",
    name: "Dell UltraSharp U2723QE 4K",
    brand: "Dell",
    category: "monitors",
    subcategory: "professional-monitor",
    price: 549,
    stock: 14,
    rating: 4.7,
    reviewCount: 692,
    tags: ["monitor", "dell", "ultrasharp", "4k", "ips-black", "usb-c", "productivity"],
    blurb: "The productivity benchmark: 4K IPS Black contrast and a full USB-C hub.",
    description:
      "The UltraSharp U2723QE is the monitor to dock a laptop to. Its IPS Black panel doubles typical IPS contrast for deeper blacks, while 90 W USB-C power delivery, a built-in KVM, and a full USB hub declutter your desk.",
    highlights: [
      "IPS Black panel with 2000:1 contrast",
      "90 W USB-C power delivery + hub",
      "Built-in KVM switch",
      "98% DCI-P3 colour coverage",
    ],
    specs: {
      Display: "27\" IPS Black, 3840x2160",
      "Refresh rate": "60 Hz",
      Contrast: "2000:1",
      Colour: "98% DCI-P3, 100% sRGB",
      Connectivity: "USB-C 90 W, HDMI, DP, RJ45, USB hub",
      KVM: "Built-in",
      Stand: "Height, tilt, swivel, pivot",
    },
    visual: "monitor",
    accent: "#0076ce",
  },
  {
    id: "aoc-24g4x",
    name: "AOC 24G4X",
    brand: "AOC",
    category: "monitors",
    subcategory: "gaming-monitor",
    price: 139,
    stock: 39,
    rating: 4.4,
    reviewCount: 458,
    tags: ["monitor", "gaming", "aoc", "1080p", "180hz", "ips", "budget", "esports"],
    blurb: "Esports speed on a budget: 1080p at 180 Hz for under €140.",
    description:
      "The AOC 24G4X is the budget esports pick, delivering a fast 180 Hz IPS panel at an unbeatable price. Low input lag and adaptive sync make it perfect for competitive shooters paired with a mid-range GPU.",
    highlights: [
      "24\" FHD IPS at 180 Hz",
      "1 ms GtG response",
      "Adaptive Sync + low input lag",
      "Unbeatable price for the speed",
    ],
    specs: {
      Display: "23.8\" IPS, 1920x1080",
      "Refresh rate": "180 Hz",
      "Response time": "1 ms GtG",
      "Adaptive sync": "Adaptive Sync (FreeSync/G-Sync Compatible)",
      HDR: "HDR10",
      Inputs: "2x HDMI 2.0, 1x DisplayPort 1.4",
      Stand: "Tilt",
    },
    visual: "monitor",
    accent: "#e02b20",
  },

  // ----------------------------------------------------------------- audio
  {
    id: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "audio",
    subcategory: "anc-headphones",
    price: 299,
    originalPrice: 369,
    stock: 23,
    rating: 4.8,
    reviewCount: 3142,
    tags: ["headphones", "sony", "anc", "wireless", "bluetooth", "travel"],
    blurb: "The industry-standard noise cancellers, now at their best price yet.",
    description:
      "The WH-1000XM5 remains the benchmark for wireless noise cancelling, with eight microphones and two processors silencing planes, trains, and open offices. Thirty hours of battery and superb call quality seal the deal.",
    highlights: [
      "Class-leading noise cancelling",
      "30 h battery with quick charge",
      "Crystal-clear call quality",
      "Multipoint Bluetooth connection",
    ],
    specs: {
      Type: "Over-ear, closed back",
      "Noise cancelling": "Dual-processor ANC, 8 mics",
      Battery: "30 h (ANC on), 3 min charge = 3 h",
      Bluetooth: "5.2, multipoint, LDAC",
      Driver: "30 mm carbon-fibre composite",
      Weight: "250 g",
    },
    visual: "headset",
    accent: "#2b2b2b",
  },
  {
    id: "airpods-pro-2",
    name: "Apple AirPods Pro 2 (USB-C)",
    brand: "Apple",
    category: "audio",
    subcategory: "anc-earbuds",
    price: 249,
    stock: 35,
    rating: 4.8,
    reviewCount: 2876,
    tags: ["earbuds", "apple", "airpods", "anc", "wireless", "usb-c"],
    blurb: "Apple's flagship earbuds with adaptive ANC and built-in hearing health features.",
    description:
      "The AirPods Pro 2 pack twice the noise cancellation of the original with Adaptive Audio that blends ANC and transparency intelligently. With the H2 chip, Personalized Spatial Audio, and hearing health features, they are the default earbuds for iPhone owners.",
    highlights: [
      "2x stronger ANC with Adaptive Audio",
      "H2 chip with Personalized Spatial Audio",
      "Hearing aid and hearing test features",
      "6 h playback, 30 h with case",
    ],
    specs: {
      Type: "In-ear, ANC",
      Chip: "Apple H2",
      Battery: "6 h (buds), 30 h with case",
      Charging: "USB-C, MagSafe, Qi",
      "Water resistance": "IP54",
      Features: "Adaptive Audio, Conversation Awareness",
    },
    visual: "earbuds",
    accent: "#f5f5f7",
  },
  {
    id: "hyperx-cloud-iii",
    name: "HyperX Cloud III",
    brand: "HyperX",
    category: "audio",
    subcategory: "gaming-headset",
    price: 99,
    stock: 28,
    rating: 4.6,
    reviewCount: 1241,
    tags: ["headset", "gaming", "hyperx", "wired", "microphone", "comfort"],
    blurb: "The legendary comfort of the Cloud line with a clearer mic and angled 53 mm drivers.",
    description:
      "The Cloud III continues HyperX's reputation for the most comfortable gaming headsets around. Angled 53 mm drivers deliver precise positional audio, and the redesigned 10 mm mic makes your callouts crisp on any platform.",
    highlights: [
      "Famous HyperX memory-foam comfort",
      "Angled 53 mm drivers",
      "Crystal-clear detachable mic",
      "Works on PC, console, and mobile",
    ],
    specs: {
      Type: "Over-ear, closed back, wired",
      Driver: "53 mm dynamic, angled",
      Microphone: "10 mm detachable, noise cancelling",
      Connection: "3.5 mm, USB-C, USB-A",
      Compatibility: "PC, PS5, Xbox, Switch, mobile",
      Weight: "303 g",
    },
    visual: "headset",
    accent: "#e21836",
  },
  {
    id: "steelseries-arctis-nova-7",
    name: "SteelSeries Arctis Nova 7 Wireless",
    brand: "SteelSeries",
    category: "audio",
    subcategory: "gaming-headset",
    price: 179,
    stock: 17,
    rating: 4.5,
    reviewCount: 923,
    tags: ["headset", "gaming", "steelseries", "wireless", "bluetooth", "microphone"],
    blurb: "Dual wireless gaming audio: 2.4 GHz and Bluetooth at the same time, 38-hour battery.",
    description:
      "The Arctis Nova 7 connects via low-latency 2.4 GHz and Bluetooth simultaneously, so you can game while staying on a call or listening to music. The Nova acoustic system and 38-hour battery make it a do-everything wireless headset.",
    highlights: [
      "Simultaneous 2.4 GHz + Bluetooth",
      "38 h battery, USB-C fast charge",
      "Nova acoustic system with 360° audio",
      "ClearCast Gen 2 retractable mic",
    ],
    specs: {
      Type: "Over-ear, wireless",
      Connection: "2.4 GHz USB-C dongle + Bluetooth 5.0",
      Battery: "38 h",
      Driver: "40 mm neodymium",
      Microphone: "ClearCast Gen 2, retractable",
      Compatibility: "PC, PS5, Switch, mobile",
      Weight: "325 g",
    },
    visual: "headset",
    accent: "#ff5200",
  },
  {
    id: "jbl-flip-6",
    name: "JBL Flip 6",
    brand: "JBL",
    category: "audio",
    subcategory: "bluetooth-speaker",
    price: 109,
    stock: 44,
    rating: 4.7,
    reviewCount: 2654,
    tags: ["speaker", "jbl", "bluetooth", "portable", "waterproof", "bass"],
    blurb: "The take-anywhere Bluetooth speaker: big JBL sound, IP67 waterproof, 12-hour battery.",
    description:
      "The Flip 6 is the portable speaker you see at every summer cottage for a reason. A racetrack woofer and separate tweeter pump out surprisingly big sound, and the IP67 rating means sauna terraces and lake trips are no problem.",
    highlights: [
      "Bold JBL Original Pro sound",
      "IP67 waterproof and dustproof",
      "12 h battery life",
      "PartyBoost speaker pairing",
    ],
    specs: {
      Output: "30 W (20 W woofer + 10 W tweeter)",
      Battery: "12 h playtime",
      "Water resistance": "IP67",
      Bluetooth: "5.1",
      Charging: "USB-C, 2.5 h full charge",
      Weight: "550 g",
    },
    visual: "speaker",
    accent: "#ff3300",
  },

  // ------------------------------------------------------------ accessories
  {
    id: "logitech-g-pro-x-superlight-2",
    name: "Logitech G Pro X Superlight 2",
    brand: "Logitech",
    category: "accessories",
    subcategory: "gaming-mouse",
    price: 159,
    stock: 21,
    rating: 4.8,
    reviewCount: 1387,
    tags: ["mouse", "gaming", "logitech", "wireless", "esports", "lightweight"],
    blurb: "The esports-standard wireless mouse: 60 grams, HERO 2 sensor, 95-hour battery.",
    description:
      "The G Pro X Superlight 2 is the mouse you will see on most pro players' desks. At just 60 grams with the flawless HERO 2 sensor and LIGHTSPEED wireless, it gets out of the way and lets your aim do the talking.",
    highlights: [
      "Only 60 g",
      "HERO 2 sensor, 32000 DPI",
      "LIGHTSPEED wireless, 95 h battery",
      "LIGHTFORCE hybrid optical switches",
    ],
    specs: {
      Weight: "60 g",
      Sensor: "HERO 2, up to 32000 DPI",
      "Polling rate": "Up to 2000 Hz",
      Connection: "LIGHTSPEED wireless, USB-C",
      Battery: "95 h",
      Buttons: "5 programmable",
    },
    visual: "mouse",
    accent: "#00b8fc",
  },
  {
    id: "logitech-mx-master-3s",
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    category: "accessories",
    subcategory: "productivity-mouse",
    price: 99,
    stock: 32,
    rating: 4.8,
    reviewCount: 2918,
    tags: ["mouse", "logitech", "productivity", "wireless", "ergonomic", "quiet"],
    blurb: "The productivity mouse, perfected: silent clicks, MagSpeed wheel, works on glass.",
    description:
      "The MX Master 3S is the default recommendation for anyone who works at a desk. The electromagnetic MagSpeed wheel scrolls 1000 lines per second, the 8K sensor tracks even on glass, and the new switches click 90% quieter.",
    highlights: [
      "90% quieter clicks",
      "MagSpeed electromagnetic scroll wheel",
      "8000 DPI sensor, tracks on glass",
      "Connects to 3 devices, 70-day battery",
    ],
    specs: {
      Sensor: "Darkfield 8000 DPI, works on glass",
      "Scroll wheel": "MagSpeed, 1000 lines/s",
      Connection: "Bluetooth, Logi Bolt, 3 devices",
      Battery: "70 days, USB-C quick charge",
      Buttons: "7 programmable",
      Weight: "141 g",
    },
    visual: "mouse",
    accent: "#6b7280",
  },
  {
    id: "keychron-k8-pro",
    name: "Keychron K8 Pro",
    brand: "Keychron",
    category: "accessories",
    subcategory: "mechanical-keyboard",
    price: 109,
    stock: 24,
    rating: 4.6,
    reviewCount: 1054,
    tags: ["keyboard", "keychron", "mechanical", "wireless", "hot-swap", "qmk", "tenkeyless"],
    blurb: "The enthusiast-friendly wireless TKL: hot-swappable switches and full QMK/VIA support.",
    description:
      "The K8 Pro brings enthusiast keyboard features to a sensible price. Hot-swappable Gateron Pro switches, QMK/VIA remapping, and Bluetooth for three devices make it equally at home on a Mac or PC desk.",
    highlights: [
      "Hot-swappable switch sockets",
      "QMK/VIA open-source firmware",
      "Bluetooth 5.1 for 3 devices + wired",
      "Mac and Windows keycaps included",
    ],
    specs: {
      Layout: "Tenkeyless (87 keys), ISO/ANSI",
      Switches: "Gateron G Pro, hot-swappable",
      Connection: "Bluetooth 5.1, USB-C wired",
      Battery: "4000 mAh, up to 100 h",
      Backlight: "RGB, south-facing",
      Firmware: "QMK/VIA",
      Frame: "Aluminium",
    },
    visual: "keyboard",
    accent: "#e0a126",
  },
  {
    id: "razer-blackwidow-v4",
    name: "Razer BlackWidow V4",
    brand: "Razer",
    category: "accessories",
    subcategory: "gaming-keyboard",
    price: 169,
    stock: 15,
    rating: 4.5,
    reviewCount: 768,
    tags: ["keyboard", "gaming", "razer", "mechanical", "rgb", "macro"],
    blurb: "A full-size mechanical gaming board with Razer's green switches and wraparound RGB.",
    description:
      "The BlackWidow V4 is Razer's classic gaming keyboard evolved: tactile Razer Green switches, six dedicated macro keys, and a plush magnetic wrist rest. Chroma RGB underglow wraps the whole deck in light.",
    highlights: [
      "Razer Green tactile mechanical switches",
      "6 dedicated macro keys + command dial",
      "Chroma RGB with underglow",
      "Magnetic plush wrist rest included",
    ],
    specs: {
      Layout: "Full-size, ISO/ANSI",
      Switches: "Razer Green tactile",
      "Polling rate": "1000 Hz",
      Lighting: "Razer Chroma RGB + underglow",
      "Macro keys": "6 dedicated",
      Connection: "USB-C, braided cable",
      "Wrist rest": "Magnetic, included",
    },
    visual: "keyboard",
    accent: "#44d62c",
  },
  {
    id: "anker-737-gan-charger",
    name: "Anker 737 GaNPrime 120W Charger",
    brand: "Anker",
    category: "accessories",
    subcategory: "charger",
    price: 89,
    stock: 47,
    rating: 4.7,
    reviewCount: 1532,
    tags: ["charger", "anker", "gan", "usb-c", "120w", "travel", "fast-charging"],
    blurb: "One pocket-size brick to charge your laptop, phone, and earbuds at once.",
    description:
      "The Anker 737 GaNPrime squeezes 120 W into a charger smaller than most laptop bricks. Two USB-C ports and one USB-A share power intelligently, so it can fast-charge a MacBook, a phone, and earbuds simultaneously.",
    highlights: [
      "120 W total from a pocketable brick",
      "2x USB-C + 1x USB-A",
      "PowerIQ 4.0 smart power allocation",
      "GaN tech runs cool and efficient",
    ],
    specs: {
      Output: "120 W max total",
      Ports: "2x USB-C (100 W max), 1x USB-A (22.5 W)",
      Technology: "GaNPrime, PowerIQ 4.0",
      Input: "100-240 V",
      Size: "80 x 43 x 32 mm",
      Weight: "187 g",
    },
    visual: "charger",
    accent: "#00a7e1",
  },
  {
    id: "tplink-archer-txe75e",
    name: "TP-Link Archer TXE75E Wi-Fi 6E PCIe Adapter",
    brand: "TP-Link",
    category: "accessories",
    subcategory: "wifi-adapter",
    price: 79,
    stock: 40,
    rating: 4.5,
    reviewCount: 612,
    tags: ["wifi", "tp-link", "wifi-6e", "pcie", "adapter", "bluetooth", "network"],
    blurb: "Add tri-band Wi-Fi 6E and Bluetooth 5.3 to any desktop over PCIe.",
    description:
      "The Archer TXE75E brings tri-band Wi-Fi 6E to desktops that lack built-in wireless, opening the clean 6 GHz band for lag-free gaming and streaming. A heatsink-equipped high-gain antenna keeps the signal stable, and Bluetooth 5.3 is included for your peripherals.",
    highlights: [
      "Adds tri-band Wi-Fi 6E to any desktop",
      "6 GHz band for low-latency gaming",
      "Bluetooth 5.3 included",
      "High-gain antenna with heatsink base",
    ],
    specs: {
      "Wi-Fi standard": "Wi-Fi 6E (802.11ax), tri-band",
      "Max speed": "5400 Mbps (574 + 2402 + 2402)",
      Bluetooth: "5.3",
      Interface: "PCIe x1",
      Antenna: "High-gain dual-band with heatsink base",
      "OS support": "Windows 11 / 10 (64-bit)",
    },
    visual: "wifi-adapter",
    accent: "#1ea7c4",
  },

  // ------------------------------------------------------------- smart-home
  {
    id: "echo-dot-5",
    name: "Amazon Echo Dot (5th Gen)",
    brand: "Amazon",
    category: "smart-home",
    subcategory: "smart-speaker",
    price: 59,
    stock: 53,
    rating: 4.6,
    reviewCount: 3186,
    tags: ["smart-home", "amazon", "alexa", "speaker", "voice-assistant"],
    blurb: "The best-selling smart speaker: Alexa, surprisingly good sound, tiny footprint.",
    description:
      "The 5th-gen Echo Dot delivers clearer vocals and deeper bass than any Dot before it. Alexa controls your lights, timers, and music, while the built-in temperature sensor enables clever smart-home automations.",
    highlights: [
      "Improved audio with deeper bass",
      "Alexa voice control for your home",
      "Built-in temperature sensor",
      "Eero Wi-Fi extender built in",
    ],
    specs: {
      Speaker: "44 mm front-firing driver",
      Assistant: "Amazon Alexa",
      Sensors: "Temperature, tap gesture",
      Connectivity: "Wi-Fi 5, Bluetooth LE, Matter",
      Ports: "Power only",
      Size: "100 x 100 x 89 mm",
    },
    visual: "smart-home",
    accent: "#00caff",
  },
  {
    id: "nest-hub-2",
    name: "Google Nest Hub (2nd Gen)",
    brand: "Google",
    category: "smart-home",
    subcategory: "smart-display",
    price: 99,
    stock: 27,
    rating: 4.5,
    reviewCount: 1764,
    tags: ["smart-home", "google", "assistant", "display", "sleep-tracking"],
    blurb: "A 7-inch smart display that runs your home, shows your photos, and tracks your sleep.",
    description:
      "The Nest Hub 2nd Gen puts Google Assistant on a 7-inch touchscreen that doubles as a gorgeous photo frame. Soli radar-based Sleep Sensing tracks your rest with no wearable, and Matter support ties your smart home together.",
    highlights: [
      "7\" touchscreen with Google Assistant",
      "Contactless Sleep Sensing with Soli radar",
      "Works as a digital photo frame",
      "Matter and Thread support",
    ],
    specs: {
      Display: "7\" touchscreen, 1024x600",
      Assistant: "Google Assistant",
      Sensors: "Soli radar, ambient light",
      Speaker: "43.5 mm full-range driver",
      Connectivity: "Wi-Fi, Bluetooth 5.0, Thread, Matter",
      Size: "177 x 120 x 69 mm",
    },
    visual: "smart-home",
    accent: "#f4b400",
  },
  {
    id: "philips-hue-starter-kit",
    name: "Philips Hue White & Color Starter Kit",
    brand: "Philips",
    category: "smart-home",
    subcategory: "smart-lighting",
    price: 159,
    originalPrice: 199,
    stock: 19,
    rating: 4.8,
    reviewCount: 2241,
    tags: ["smart-home", "philips", "hue", "lighting", "rgb", "matter", "zigbee"],
    blurb: "Three colour-changing bulbs and the Hue Bridge — everything to start smart lighting.",
    description:
      "This starter kit includes three White & Color Ambiance E27 bulbs and the Hue Bridge that unlocks the full ecosystem. Set scenes, sync lights to movies and games, and automate your whole home's lighting from one app.",
    highlights: [
      "3x E27 bulbs with 16 million colours",
      "Hue Bridge included for full features",
      "Works with Alexa, Google, HomeKit, Matter",
      "Sync lighting to movies, music, and games",
    ],
    specs: {
      Contents: "3x E27 White & Color bulbs + Hue Bridge",
      Brightness: "1100 lumen per bulb",
      Colours: "16 million + warm-to-cool white",
      Protocol: "Zigbee via Bridge, Bluetooth direct",
      Compatibility: "Alexa, Google Home, Apple HomeKit, Matter",
      Lifetime: "25,000 h per bulb",
    },
    visual: "smart-home",
    accent: "#7e57c2",
  },
  {
    id: "tapo-p115-smart-plug",
    name: "TP-Link Tapo P115 Smart Plug",
    brand: "TP-Link",
    category: "smart-home",
    subcategory: "smart-plug",
    price: 17,
    stock: 58,
    rating: 4.7,
    reviewCount: 2389,
    tags: ["smart-home", "tp-link", "tapo", "smart-plug", "energy-monitoring", "wifi"],
    blurb: "A tiny Wi-Fi smart plug with energy monitoring — automate anything for under €20.",
    description:
      "The Tapo P115 turns any appliance into a smart device, with scheduling, away modes, and voice control. Built-in energy monitoring shows exactly what each device costs to run — handy with Nordic electricity prices.",
    highlights: [
      "Real-time energy monitoring",
      "Schedules, timers, and away mode",
      "Works with Alexa and Google Home",
      "Compact design fits double sockets",
    ],
    specs: {
      "Max load": "16 A / 3680 W",
      "Energy monitoring": "Yes, real-time and history",
      Connectivity: "Wi-Fi 2.4 GHz",
      Compatibility: "Alexa, Google Home",
      Plug: "Type F (Schuko)",
      Size: "59 x 38 x 33 mm",
    },
    visual: "smart-home",
    accent: "#4acbd6",
  },
];

export const featuredIds: string[] = [
  "iphone-16-pro",
  "nzxt-player-three",
  "lg-ultragear-27gs75q",
  "legion-pro-5-16",
];

export const categoryMeta: Record<Category, { label: string; tagline: string }> = {
  phones: {
    label: "Phones",
    tagline: "Flagships and smart budget picks from every major brand.",
  },
  laptops: {
    label: "Laptops",
    tagline: "From featherweight ultrabooks to RTX-powered gaming rigs.",
  },
  desktops: {
    label: "Desktop PCs",
    tagline: "Prebuilt gaming towers, ready to play out of the box.",
  },
  components: {
    label: "PC Components",
    tagline: "CPUs, GPUs, and everything you need to build your own.",
  },
  monitors: {
    label: "Monitors",
    tagline: "High-refresh gaming panels and pin-sharp 4K workspaces.",
  },
  audio: {
    label: "Audio",
    tagline: "Headphones, earbuds, and speakers for play and focus.",
  },
  accessories: {
    label: "Accessories",
    tagline: "Mice, keyboards, and chargers that complete your setup.",
  },
  "smart-home": {
    label: "Smart Home",
    tagline: "Speakers, lights, and plugs that make your home smarter.",
  },
};
