import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "phone-nordic-x1",
    name: "Nordic X1 5G",
    brand: "Nordic Mobile",
    category: "phones",
    subcategory: "Android phones",
    price: 449,
    originalPrice: 549,
    stock: 18,
    rating: 4.5,
    tags: ["deal", "camera", "5g", "value"],
    description: "A balanced 5G phone with a bright OLED screen, strong battery life, and a clean Android build.",
    specs: { display: "6.4 in OLED", storage: "256 GB", camera: "50 MP", battery: "5100 mAh" },
    visual: "phone",
    accent: "#2d7ff9",
  },
  {
    id: "phone-orbit-pro",
    name: "Orbit Pro 15",
    brand: "Orbit",
    category: "phones",
    subcategory: "Premium phones",
    price: 999,
    stock: 9,
    rating: 4.8,
    tags: ["premium", "camera", "5g"],
    description: "Flagship performance, long software support, and a pro camera system for video-heavy creators.",
    specs: { display: "6.7 in LTPO", storage: "256 GB", camera: "Triple 48 MP", chipset: "A19 Pro" },
    visual: "phone",
    accent: "#121826",
  },
  {
    id: "phone-pixelwave-a",
    name: "PixelWave A",
    brand: "PixelWave",
    category: "phones",
    subcategory: "Android phones",
    price: 379,
    originalPrice: 429,
    stock: 0,
    rating: 4.2,
    tags: ["deal", "camera", "unavailable"],
    description: "A camera-first midrange phone with smart photo tools. Currently out of stock.",
    specs: { display: "6.1 in OLED", storage: "128 GB", camera: "64 MP", battery: "4600 mAh" },
    visual: "phone",
    accent: "#0f9f8f",
  },
  {
    id: "laptop-legion-16",
    name: "Legion Spark 16",
    brand: "Lenovo",
    category: "laptops",
    subcategory: "Gaming laptops",
    price: 1199,
    originalPrice: 1399,
    stock: 7,
    rating: 4.6,
    tags: ["gaming", "deal", "rtx", "laptop"],
    description: "A 16-inch gaming laptop tuned for esports and high-refresh play without stepping into luxury pricing.",
    specs: { cpu: "Intel Core i5-13450HX", gpu: "RTX 5050 8 GB", ram: "16 GB DDR5", storage: "512 GB SSD" },
    compatibility: { memory: "DDR5", estimatedWatts: 180 },
    visual: "laptop",
    accent: "#6d5dfc",
  },
  {
    id: "desktop-aurora-r5",
    name: "Aurora R5 Gaming Tower",
    brand: "Aster",
    category: "desktops",
    subcategory: "Gaming desktops",
    price: 1399,
    originalPrice: 1549,
    stock: 6,
    rating: 4.7,
    tags: ["gaming", "deal", "rtx", "desktop"],
    description: "A quiet RTX tower for 1440p gaming, streaming, and upgrade-friendly storage expansion.",
    specs: { cpu: "Ryzen 7 9700X", gpu: "RTX 5070 12 GB", ram: "32 GB DDR5", storage: "1 TB NVMe" },
    compatibility: { cpuSocket: "AM5", memory: "DDR5", estimatedWatts: 410 },
    visual: "desktop",
    accent: "#00a876",
  },
  {
    id: "desktop-mini-forge",
    name: "MiniForge 4060",
    brand: "Aster",
    category: "desktops",
    subcategory: "Compact gaming desktops",
    price: 899,
    stock: 11,
    rating: 4.3,
    tags: ["gaming", "value", "desktop"],
    description: "A compact 1080p gaming desktop for esports, school work, and light content creation.",
    specs: { cpu: "Ryzen 5 7600", gpu: "RTX 4060 8 GB", ram: "16 GB DDR5", storage: "1 TB NVMe" },
    compatibility: { cpuSocket: "AM5", memory: "DDR5", estimatedWatts: 320 },
    visual: "desktop",
    accent: "#e06343",
  },
  {
    id: "cpu-ryzen-7800x3d",
    name: "Ryzen 7 7800X3D",
    brand: "AMD",
    category: "components",
    subcategory: "CPU",
    price: 369,
    stock: 14,
    rating: 4.9,
    tags: ["gaming", "cpu", "am5"],
    description: "A gaming-focused AM5 CPU with 3D V-Cache for high frame rates in simulation and competitive titles.",
    specs: { cores: 8, threads: 16, socket: "AM5", memory: "DDR5" },
    compatibility: { cpuSocket: "AM5", memory: "DDR5", estimatedWatts: 120 },
    visual: "chip",
    accent: "#ef5b2a",
  },
  {
    id: "cpu-intel-14700k",
    name: "Core i7-14700K",
    brand: "Intel",
    category: "components",
    subcategory: "CPU",
    price: 389,
    stock: 10,
    rating: 4.7,
    tags: ["gaming", "cpu", "lga1700"],
    description: "A high-clock Intel CPU for gaming and productivity builds on LGA1700 motherboards.",
    specs: { cores: 20, threads: 28, socket: "LGA1700", memory: "DDR4/DDR5" },
    compatibility: { cpuSocket: "LGA1700", estimatedWatts: 190 },
    visual: "chip",
    accent: "#2975d1",
  },
  {
    id: "board-b650-pulse",
    name: "B650 Pulse WiFi",
    brand: "MSI",
    category: "components",
    subcategory: "Motherboard",
    price: 189,
    stock: 15,
    rating: 4.5,
    tags: ["motherboard", "am5", "wifi"],
    description: "An AM5 DDR5 motherboard with WiFi 7, three M.2 slots, and a clean upgrade path.",
    specs: { socket: "AM5", memory: "DDR5", size: "ATX", wifi: true },
    compatibility: { motherboardSocket: "AM5", memory: "DDR5" },
    visual: "board",
    accent: "#2d7ff9",
  },
  {
    id: "board-z790-edge",
    name: "Z790 Edge WiFi",
    brand: "MSI",
    category: "components",
    subcategory: "Motherboard",
    price: 229,
    originalPrice: 259,
    stock: 8,
    rating: 4.6,
    tags: ["motherboard", "lga1700", "wifi", "deal"],
    description: "A feature-rich LGA1700 board with fast networking, DDR5, and strong VRM cooling.",
    specs: { socket: "LGA1700", memory: "DDR5", size: "ATX", wifi: true },
    compatibility: { motherboardSocket: "LGA1700", memory: "DDR5" },
    visual: "board",
    accent: "#252a34",
  },
  {
    id: "gpu-rtx-5070",
    name: "GeForce RTX 5070 Aero",
    brand: "NVIDIA",
    category: "components",
    subcategory: "GPU",
    price: 619,
    stock: 5,
    rating: 4.6,
    tags: ["gaming", "gpu", "1440p"],
    description: "A 1440p-first GPU with modern ray tracing support and efficient dual-fan cooling.",
    specs: { memory: "12 GB GDDR7", length: "280 mm", recommendedPsu: "650 W" },
    compatibility: { gpuLengthMm: 280, estimatedWatts: 250 },
    visual: "board",
    accent: "#00a876",
  },
  {
    id: "psu-750-gold",
    name: "VoltMax 750 Gold",
    brand: "VoltMax",
    category: "components",
    subcategory: "Power supply",
    price: 119,
    stock: 21,
    rating: 4.4,
    tags: ["psu", "gaming"],
    description: "A quiet fully modular 750 W power supply with enough headroom for upper-midrange GPUs.",
    specs: { wattage: "750 W", efficiency: "80+ Gold", modular: true },
    compatibility: { psuWatts: 750 },
    visual: "peripheral",
    accent: "#f2a900",
  },
  {
    id: "monitor-omni-27",
    name: "OmniView 27 QHD 165",
    brand: "Viewlab",
    category: "accessories",
    subcategory: "Monitor",
    price: 249,
    originalPrice: 299,
    stock: 16,
    rating: 4.5,
    tags: ["gaming", "monitor", "deal", "1440p"],
    description: "A 27-inch QHD fast IPS monitor with 165 Hz refresh for smooth play and crisp text.",
    specs: { size: "27 in", resolution: "2560 x 1440", refresh: "165 Hz", panel: "IPS" },
    visual: "peripheral",
    accent: "#8d5cf6",
  },
  {
    id: "headset-wave-7",
    name: "Wave 7 Wireless Headset",
    brand: "Aural",
    category: "accessories",
    subcategory: "Headset",
    price: 99,
    stock: 24,
    rating: 4.3,
    tags: ["gaming", "wireless", "audio"],
    description: "Low-latency wireless audio, a clear boom mic, and plush pads for long sessions.",
    specs: { connection: "2.4 GHz + Bluetooth", battery: "38 hours", mic: "Detachable" },
    visual: "peripheral",
    accent: "#21a0a0",
  },
  {
    id: "home-hub-mini",
    name: "NestPoint Mini Hub",
    brand: "NestPoint",
    category: "smart-home",
    subcategory: "Smart hubs",
    price: 79,
    stock: 19,
    rating: 4.2,
    tags: ["smart-home", "voice", "value"],
    description: "A compact hub for lights, routines, and voice control across Matter-compatible devices.",
    specs: { protocols: "Matter, Thread, WiFi", speaker: "Mono", display: false },
    visual: "home",
    accent: "#0f9f8f",
  },
];

export const featuredIds = ["desktop-aurora-r5", "phone-nordic-x1", "monitor-omni-27", "laptop-legion-16"];
